/**
 * UBL 2.1 XML Generator for Egyptian Tax Authority (ETA) E-Receipt System
 * 
 * This module generates compliant XML documents for the Egyptian E-Receipt system
 * following UBL 2.1 standards and ETA specifications.
 */

export interface ETADocumentType {
  type: '389' | '381' | '383' | '384' | '388'; // 389: Receipt, 381: Invoice, 383: Credit Note, 384: Debit Note, 388: Simplified Invoice
}

export interface ETACompanyInfo {
  companyName: string;
  taxRegistrationNumber: string;
  branchCode: string;
  commercialRegister?: string;
  address: string;
  city: string;
  governorate: string;
  postalCode?: string;
  phone: string;
  email?: string;
}

export interface ETACustomerInfo {
  name?: string;
  taxRegistrationNumber?: string;
  address?: string;
  phone?: string;
  email?: string;
}

export interface ETALineItem {
  name: string;
  code?: string; // Product code/barcode
  unitType: string; // EA, KG, etc.
  quantity: number;
  unitPrice: number;
  netPrice: number;
  taxRate: number; // 0.14 for 14% VAT
  taxAmount: number;
  totalAmount: number;
  discountAmount?: number;
  itemType: string; // GS1, GPL, etc.
}

export interface ETAPaymentData {
  method: string; // cash, card, instapay, wallet, etc.
  amount: number;
  referenceNumber?: string;
}

export interface ETADocumentData {
  documentType: ETADocumentType;
  documentUuid: string; // Will be generated by ETA
  issueDate: Date; // Document date/time
  currency: string; // EGP
  seller: ETACompanyInfo;
  buyer?: ETACustomerInfo;
  lineItems: ETALineItem[];
  subtotal: number;
  totalTaxAmount: number;
  discountAmount: number;
  totalAmount: number;
  paymentMethods: ETAPaymentData[];
  notes?: string;
  // Credit Note specific fields
  originalDocumentUuid?: string; // For Credit Notes: UUID of the document being credited
  creditReason?: string; // For Credit Notes: Reason for the credit
}

/**
 * Generate UBL 2.1 compliant XML for Egyptian Tax Authority
 */
export function generateUBLXML(data: ETADocumentData): string {
  const { documentType, documentUuid, issueDate, currency, seller, buyer, lineItems, subtotal, totalTaxAmount, discountAmount, totalAmount, paymentMethods, notes, originalDocumentUuid, creditReason } = data;

  // Format date to ISO 8601
  const formattedDate = issueDate.toISOString();
  const formattedDateWithoutTime = issueDate.toISOString().split('T')[0];

  // Generate document type code
  const docTypeCode = documentType.type;

  // Calculate totals
  const totalDiscountAmount = discountAmount || 0;
  const payableAmount = totalAmount;

  // Build Billing Reference for Credit Notes (required by ETA)
  let billingReferenceXML = '';
  if (docTypeCode === '383' && originalDocumentUuid) {
    // 383 is Credit Note
    billingReferenceXML = `
  <cac:BillingReference>
    <cac:InvoiceDocumentReference>
      <cbc:ID>${originalDocumentUuid}</cbc:ID>
    </cac:InvoiceDocumentReference>
  </cac:BillingReference>`;
  }

  // Build line items XML
  const lineItemsXML = lineItems.map((item, index) => {
    const itemIndex = index + 1;
    return `
  <cac:InvoiceLine>
    <cbc:ID>${itemIndex}</cbc:ID>
    <cbc:InvoicedQuantity unitCode="${item.unitType}">${item.quantity}</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="${currency}">${item.netPrice.toFixed(2)}</cbc:LineExtensionAmount>
    <cac:Item>
      <cbc:Description>${escapeXML(item.name)}</cbc:Description>
      <cbc:Name>${escapeXML(item.name)}</cbc:Name>
      <cac:SellersItemIdentification>
        <cbc:ID>${item.code || ''}</cbc:ID>
      </cac:SellersItemIdentification>
      <cac:CommodityClassification>
        <cbc:ItemClassificationCode listID="UNSPSC" listAgencyName="GS1">${item.itemType}</cbc:ItemClassificationCode>
      </cac:CommodityClassification>
      <cac:ClassifiedTaxCategory>
        <cbc:ID>${(item.taxRate * 100).toFixed(0)}</cbc:ID>
        <cbc:Percent>${(item.taxRate * 100).toFixed(2)}</cbc:Percent>
        <cbc:TaxScheme>${seller.taxRegistrationNumber}</cbc:TaxScheme>
      </cac:ClassifiedTaxCategory>
    </cac:Item>
    <cac:Price>
      <cbc:PriceAmount currencyID="${currency}">${item.unitPrice.toFixed(2)}</cbc:PriceAmount>
    </cac:Price>
    <cac:DocumentReference>
      <cbc:ID>1</cbc:ID>
      <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
    </cac:DocumentReference>
  </cac:InvoiceLine>`;
  }).join('');

  // Build payment means XML
  const paymentMeansXML = paymentMethods.map((payment, index) => {
    const paymentCode = getPaymentCode(payment.method);
    return `
  <cac:PaymentMeans>
    <cbc:PaymentMeansCode>${paymentCode}</cbc:PaymentMeansCode>
    <cbc:PaymentAmount currencyID="${currency}">${payment.amount.toFixed(2)}</cbc:PaymentAmount>
    ${payment.referenceNumber ? `<cbc:PaymentID>${escapeXML(payment.referenceNumber)}</cbc:PaymentID>` : ''}
  </cac:PaymentMeans>`;
  }).join('');

  // Build tax totals XML
  const taxTotalXML = `
  <cac:TaxTotal>
    <cbc:TaxAmount currencyID="${currency}">${totalTaxAmount.toFixed(2)}</cbc:TaxAmount>
  </cac:TaxTotal>`;

  // Build legal monetary total
  const legalMonetaryTotalXML = `
  <cac:LegalMonetaryTotal>
    <cbc:LineExtensionAmount currencyID="${currency}">${subtotal.toFixed(2)}</cbc:LineExtensionAmount>
    <cbc:TaxExclusiveAmount currencyID="${currency}">${(subtotal - totalDiscountAmount).toFixed(2)}</cbc:TaxExclusiveAmount>
    <cbc:TaxInclusiveAmount currencyID="${currency}">${totalAmount.toFixed(2)}</cbc:TaxInclusiveAmount>
    <cbc:AllowanceTotalAmount currencyID="${currency}">${totalDiscountAmount.toFixed(2)}</cbc:AllowanceTotalAmount>
    <cbc:PayableAmount currencyID="${currency}">${payableAmount.toFixed(2)}</cbc:PayableAmount>
  </cac:LegalMonetaryTotal>`;

  // Build seller party XML
  const sellerPartyXML = `
  <cac:AccountingSupplierParty>
    <cac:Party>
      <cbc:EndpointID schemeID="TRN">${seller.taxRegistrationNumber}</cbc:EndpointID>
      <cac:PartyIdentification>
        <cbc:ID>${seller.taxRegistrationNumber}</cbc:ID>
      </cac:PartyIdentification>
      <cac:PartyName>
        <cbc:Name>${escapeXML(seller.companyName)}</cbc:Name>
      </cac:PartyName>
      <cac:PostalAddress>
        <cbc:StreetName>${escapeXML(seller.address)}</cbc:StreetName>
        <cbc:CityName>${escapeXML(seller.city)}</cbc:CityName>
        <cbc:CountrySubentity>${escapeXML(seller.governorate)}</cbc:CountrySubentity>
        <cbc:PostalZone>${seller.postalCode || ''}</cbc:PostalZone>
        <cac:Country>
          <cbc:IdentificationCode>EG</cbc:IdentificationCode>
        </cac:Country>
      </cac:PostalAddress>
      <cac:PartyTaxScheme>
        <cbc:CompanyID>${seller.taxRegistrationNumber}</cbc:CompanyID>
        <cbc:TaxScheme>${seller.taxRegistrationNumber}</cbc:TaxScheme>
      </cac:PartyTaxScheme>
      <cac:PartyLegalEntity>
        <cbc:RegistrationName>${escapeXML(seller.companyName)}</cbc:RegistrationName>
        <cbc:CompanyID>${seller.commercialRegister || ''}</cbc:CompanyID>
      </cac:PartyLegalEntity>
      <cac:Contact>
        <cbc:Telephone>${escapeXML(seller.phone)}</cbc:Telephone>
        ${seller.email ? `<cbc:ElectronicMail>${escapeXML(seller.email)}</cbc:ElectronicMail>` : ''}
      </cac:Contact>
    </cac:Party>
  </cac:AccountingSupplierParty>`;

  // Build buyer party XML (customer)
  let buyerPartyXML = '';
  if (buyer && (buyer.name || buyer.taxRegistrationNumber)) {
    buyerPartyXML = `
  <cac:AccountingCustomerParty>
    <cac:Party>
      ${buyer.taxRegistrationNumber ? `<cbc:EndpointID schemeID="TRN">${buyer.taxRegistrationNumber}</cbc:EndpointID>` : ''}
      ${buyer.taxRegistrationNumber ? `
      <cac:PartyIdentification>
        <cbc:ID>${buyer.taxRegistrationNumber}</cbc:ID>
      </cac:PartyIdentification>` : ''}
      ${buyer.name ? `
      <cac:PartyName>
        <cbc:Name>${escapeXML(buyer.name)}</cbc:Name>
      </cac:PartyName>` : ''}
      ${buyer.address ? `
      <cac:PostalAddress>
        <cbc:StreetName>${escapeXML(buyer.address)}</cbc:StreetName>
        <cac:Country>
          <cbc:IdentificationCode>EG</cbc:IdentificationCode>
        </cac:Country>
      </cac:PostalAddress>` : ''}
      ${buyer.phone ? `
      <cac:Contact>
        <cbc:Telephone>${escapeXML(buyer.phone)}</cbc:Telephone>
      </cac:Contact>` : ''}
    </cac:Party>
  </cac:AccountingCustomerParty>`;
  }

  // Build full XML document
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
         xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
         xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
         xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2">
  <ext:UBLExtensions>
    <ext:UBLExtension>
      <ext:ExtensionContent>
        <Document xmlns="urn:eta:documents:xsd">
          <IssueDate>${formattedDateWithoutTime}</IssueDate>
          <IssueTime>${formattedDate.split('T')[1]?.split('.')[0] || '00:00:00'}</IssueTime>
          <Issuer>${seller.taxRegistrationNumber}</Issuer>
          <Receiver>${buyer?.taxRegistrationNumber || ''}</Receiver>
          <DocumentType>${docTypeCode}</DocumentType>
          <Type>1</Type>
          <Version>1.0</Version>
          <Currency>${currency}</Currency>
        </Document>
      </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>
  <cbc:ID>${documentUuid}</cbc:ID>
  <cbc:IssueDate>${formattedDateWithoutTime}</cbc:IssueDate>
  <cbc:IssueTime>${formattedDate.split('T')[1]?.split('.')[0] || '00:00:00'}</cbc:IssueTime>
  <cbc:InvoiceTypeCode>${docTypeCode}</cbc:InvoiceTypeCode>
  ${notes ? `<cbc:Note>${escapeXML(notes)}</cbc:Note>` : ''}
  <cbc:DocumentCurrencyCode>${currency}</cbc:DocumentCurrencyCode>
  <cbc:BuyerReference>${seller.branchCode}</cbc:BuyerReference>
  ${sellerPartyXML}
  ${buyerPartyXML}
  ${billingReferenceXML}
  ${lineItemsXML}
  ${taxTotalXML}
  ${legalMonetaryTotalXML}
  ${paymentMeansXML}
</Invoice>`;

  return xml;
}

/**
 * Generate a UUID v4 for the ETA document
 * This will be the unique identifier for each receipt/invoice
 */
export function generateDocumentUUID(): string {
  // Generate a UUID v4
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

/**
 * Generate Credit Note data from original order data
 * This is a helper function to create Credit Note XML for refunds
 */
export function generateCreditNoteData(params: {
  originalDocumentUuid: string;
  originalOrderNumber: string;
  reason: string;
  issueDate: Date;
  seller: ETACompanyInfo;
  buyer?: ETACustomerInfo;
  refundedItems: {
    name: string;
    code?: string;
    unitType: string;
    quantity: number;
    unitPrice: number;
    netPrice: number;
    taxRate: number;
    taxAmount: number;
    totalAmount: number;
    itemType: string;
  }[];
  subtotal: number;
  totalTaxAmount: number;
  totalAmount: number;
  paymentMethod: {
    method: string;
    amount: number;
    referenceNumber?: string;
  };
}): ETADocumentData {
  return {
    documentType: { type: '383' }, // 383 = Credit Note
    documentUuid: generateDocumentUUID(),
    issueDate: params.issueDate,
    currency: 'EGP',
    seller: params.seller,
    buyer: params.buyer,
    lineItems: params.refundedItems.map(item => ({
      name: item.name,
      code: item.code,
      unitType: item.unitType,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      netPrice: item.netPrice,
      taxRate: item.taxRate,
      taxAmount: item.taxAmount,
      totalAmount: item.totalAmount,
      itemType: item.itemType,
    })),
    subtotal: params.subtotal,
    totalTaxAmount: params.totalTaxAmount,
    discountAmount: 0,
    totalAmount: params.totalAmount,
    paymentMethods: [params.paymentMethod],
    notes: `Credit Note for Order ${params.originalOrderNumber}. ${params.reason}`,
    originalDocumentUuid: params.originalDocumentUuid,
    creditReason: params.reason,
  };
}


/**
 * Map payment method to UBL payment means code
 */
function getPaymentCode(method: string): string {
  const methodMap: Record<string, string> = {
    'cash': '10', // Cash
    'card': '30', // Credit transfer
    'instapay': '30', // Credit transfer
    'wallet': '48', // Payment card
    'bank': '30', // Credit transfer
  };
  
  const normalizedMethod = method.toLowerCase().replace(/[_\s]/g, '');
  return methodMap[normalizedMethod] || '10'; // Default to cash
}

/**
 * Escape XML special characters
 */
function escapeXML(text: string): string {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Validate UBL XML structure (basic validation)
 */
export function validateUBLXML(xml: string): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  // Check for required elements
  if (!xml.includes('<Invoice')) {
    errors.push('Missing root Invoice element');
  }
  if (!xml.includes('<cbc:ID>')) {
    errors.push('Missing document ID');
  }
  if (!xml.includes('<cbc:IssueDate>')) {
    errors.push('Missing issue date');
  }
  if (!xml.includes('<cac:AccountingSupplierParty>')) {
    errors.push('Missing supplier party information');
  }
  if (!xml.includes('<cac:InvoiceLine>')) {
    errors.push('Missing invoice line items');
  }
  if (!xml.includes('<cac:LegalMonetaryTotal>')) {
    errors.push('Missing monetary total');
  }
  
  return {
    valid: errors.length === 0,
    errors
  };
}
